default:
  golem_name: painel.indicadores
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: C:/Users/Pichau/Documentos/Faculdade/OOBr/oobr-rosa/painel.indicadores-master
